// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pakkcoyfwjxxckdecdmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBha2tjb3lmd2p4eGNrZGVjZG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzYyMjYsImV4cCI6MjA2NTE1MjIyNn0.QPG6iNdhxk89V5PiVAvBcdU5ccz9eRdcZoLoqnG0RR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);